### ISSUE TITLE
Index for function definitions

### ISSUE THREAD

**Issue by geanders** [joelgrus/data-science-from-scratch#21]
An index giving the page where each custom function is defined would be very useful in navigating the book, particularly the later chapters.

**Comment by pmbaumgartner** [comment]
Seconded. This particularly helps those of us using the book as reference, rather than going through in a linear fashion. Often times I'll attempt to go through a chapter only to find that a function I need is defined in an unknown previous chapter. 

Some of this issue is solved by looking at the code on GitHub, where each program has the imports stated at the top, however this information is not made explicit in the book.

**Comment by joelgrus** [comment]
the things I do for you guys:

https://docs.google.com/spreadsheets/d/1mjGp94ehfxWOEaAFJsPiHqIeOioPH1vN1PdOE6v1az8/edit?usp=sharing

I'll think about an easier to use format

**Comment by geanders** [comment]
Thank you! This is great.
